# name: Build optimism-contract-deployer
# on:
#   workflow_dispatch:

# env:
#   PROJECT_ID: ethos-artifacts
#   REGION: us-west1
#   GAR_LOCATION: us-docker.pkg.dev/ethos-artifacts/docker

# jobs:
#   build-push:
#     name: build-push
#     runs-on: ubuntu-latest
#     permissions:
#       contents: 'read'
#       id-token: 'write'
#     steps:
#       - name: Checkout this repo
#         uses: actions/checkout@v4
#       - name: Docker Metadata Pull
#         id: meta
#         uses: docker/metadata-action@v5
#         with:
#           flavor: latest=true
#           images: |
#             us-docker.pkg.dev/ethos-artifacts/docker/infinity-contract-deployer
#           tags: |
#             type=semver,pattern={{version}}
#             type=sha,enable=true,priority=100,prefix=,suffix=,format=long
#             type=ref,enable=true,priority=600,prefix=,suffix=,event=tag
#       - id: auth
#         name: Authenticate with Google Cloud
#         uses: google-github-actions/auth@v2
#         with:
#           token_format: access_token
#           credentials_json: '${{ secrets.ARTIFACT_REGISTRY_CREDENTIALS }}'
#       - name: Login to Artifact Registry
#         uses: docker/login-action@v3
#         with:
#           registry: us-docker.pkg.dev
#           username: _json_key
#           password: '${{ secrets.ARTIFACT_REGISTRY_CREDENTIALS }}'
#       - id: docker-push-tagged
#         name: Tag Docker image and push to Google Artifact Registry
#         uses: docker/build-push-action@v6
#         with:
#           push: true
#           tags: ${{ steps.meta.outputs.tags }}
#           labels: ${{ steps.meta.outputs.labels }}
